### Importing Libraries

In [4]:
import pandas as pd
import numpy as np

### Load Test Data

In [22]:
dataset = pd.read_csv('data_test.csv')

In [24]:
dataset

,id,num1,num2,num3,num4,num5,num6,num7,num8,num9,...,cat5,cat6,cat7,cat8,cat9,cat10,cat11,cat12,cat13,cat14
0,0,0,8,0,1,0,0,0,0,0,...,1.0,NaN,0,NaN,1,1.0,1,2.0,1,65
1,1,4,5,0,0,0,1,0,0,0,...,1.0,NaN,0,0.0,11,1.0,1,0.0,1,103
2,2,5,3,0,0,0,1,0,0,0,...,1.0,NaN,0,NaN,14,1.0,1,2.0,1,29
3,3,0,6,1,0,0,0,0,0,0,...,1.0,NaN,0,NaN,1,1.0,1,2.0,1,40
4,4,5,7,0,0,0,1,0,0,0,...,1.0,NaN,0,NaN,11,1.0,1,2.0,1,101
5,5,0,6,1,0,0,0,0,0,0,...,1.0,NaN,0,NaN,11,0.0,0,2.0,1,11
6,6,0,3,0,1,0,0,0,0,0,...,1.0,NaN,0,0.0,1,1.0,1,0.0,1,10
7,8,0,0,1,0,0,0,0,0,0,...,1.0,NaN,0,NaN,11,1.0,1,2.0,1,103
8,10,0,7,0,1,0,0,0,0,0,...,0.0,1.0,1,0.0,2,NaN,0,0.0,1,104
9,11,1,6,0,0,0,1,0,0,0,...,0.0,NaN,0,NaN,4,1.0,1,2.0,1,104
10,12,0,5,1,0,0,0,0,0,0,...,1.0,NaN,0,NaN,11,1.0,0,0.0,1,103
11,14,1,4,1,0,0,0,0,0,0,...,1.0,NaN,0,NaN,7,1.0,0,2.0,1,104
12,15,1,2,0,1,0,0,0,0,0,...,0.0,1.0,0,1.0,6,1.0,1,2.0,1,104
13,18,3,3,0,1,0,0,0,0,0,...,1.0,NaN,1,NaN,1,1.0,0,1.0,1,35
14,21,0,1,1,0,0,0,0,0,0,...,0.0,NaN,0,1.0,11,1.0,1,0.0,1,104
15,23,2,2,0,0,1,0,0,0,0,...,1.0,NaN,2,NaN,0,1.0,1,2.0,1,104
16,24,2,3,0,0,1,0,0,0,0,...,1.0,NaN,0,NaN,14,1.0,1,2.0,1,60
17,25,0,0,1,0,0,0,0,0,0,...,1.0,0.0,0,1.0,11,NaN,1,2.0,1,103
18,27,3,1,1,0,0,0,0,0,0,...,1.0,NaN,0,NaN,11,1.0,1,3.0,1,16
19,29,1,4,0,1,0,0,0,0,0,...,0.0,NaN,1,NaN,0,1.0,1,2.0,1,75
20,30,0,4,1,0,0,0,0,0,0,...,1.0,1.0,0,0.0,0,1.0,0,1.0,1,78
21,31,6,1,0,0,0,1,0,0,0,...,1.0,NaN,0,1.0,11,1.0,0,0.0,1,69
22,32,0,8,0,1,0,0,0,0,0,...,0.0,0.0,1,1.0,14,1.0,1,2.0,1,104
23,33,1,2,1,0,0,0,0,0,0,...,1.0,NaN,0,NaN,1,1.0,1,3.0,1,10
24,37,5,6,0,0,0,1,0,0,0,...,1.0,NaN,0,NaN,1,1.0,0,2.0,1,25
25,38,1,0,0,1,0,0,0,0,0,...,1.0,NaN,0,NaN,0,1.0,1,0.0,1,87
26,39,5,2,0,0,1,0,0,0,0,...,1.0,1.0,0,1.0,1,0.0,1,3.0,1,74
27,40,1,3,1,0,0,0,0,0,0,...,1.0,NaN,0,NaN,14,0.0,1,2.0,1,42
28,41,0,1,0,1,0,0,0,0,0,...,1.0,NaN,0,0.0,0,1.0,0,0.0,1,34
29,42,1,7,1,0,0,0,0,0,0,...,1.0,NaN,0,NaN,6,1.0,1,0.0,1,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892786,1487982,2,3,1,0,0,0,0,0,0,...,1.0,NaN,0,0.0,11,1.0,1,0.0,1,103
892787,1487984,1,2,1,0,0,0,0,0,0,...,1.0,1.0,0,0.0,1,1.0,1,1.0,1,38
892788,1487985,3,3,0,0,1,0,0,0,0,...,1.0,NaN,0,NaN,0,1.0,1,0.0,1,78
892789,1487986,1,1,0,0,0,1,0,0,0,...,1.0,NaN,0,NaN,0,1.0,0,2.0,1,37
892790,1487987,0,5,0,0,1,0,0,0,0,...,1.0,NaN,0,1.0,6,1.0,1,0.0,1,104
892791,1487989,1,8,1,0,0,0,0,0,0,...,1.0,NaN,0,NaN,0,1.0,1,2.0,1,34
892792,1487991,1,6,1,0,0,0,0,0,0,...,0.0,NaN,0,0.0,11,1.0,1,0.0,1,53
892793,1487993,0,1,1,0,0,0,0,0,0,...,1.0,NaN,0,1.0,11,1.0,1,0.0,1,16
892794,1487995,6,7,0,0,0,1,0,0,0,...,1.0,NaN,0,0.0,1,1.0,1,0.0,1,40
892795,1487997,2,8,0,0,0,1,0,0,0,...,1.0,NaN,0,1.0,11,1.0,1,0.0,1,103
892796,1487998,0,1,0,1,0,0,0,0,0,...,1.0,0.0,0,0.0,15,1.0,1,2.0,1,97
892797,1487999,2,5,0,0,1,0,0,0,0,...,1.0,NaN,2,NaN,0,1.0,1,2.0,1,100
892798,1488000,7,4,0,0,0,1,0,0,0,...,0.0,1.0,0,1.0,15,0.0,1,2.0,1,5
892799,1488002,0,0,1,0,0,0,0,0,0,...,1.0,1.0,0,0.0,0,NaN,0,2.0,1,34
892800,1488003,1,2,0,1,0,0,0,0,0,...,0.0,NaN,0,NaN,15,1.0,1,2.0,1,5
892801,1488004,0,7,1,0,0,0,0,0,0,...,0.0,NaN,0,1.0,11,1.0,1,0.0,1,104
892802,1488006,2,2,0,1,0,0,0,0,0,...,1.0,NaN,0,0.0,14,1.0,1,0.0,1,82
892803,1488007,3,2,1,0,0,0,0,0,0,...,1.0,NaN,0,NaN,6,1.0,1,2.0,1,27
892804,1488010,4,6,1,0,0,0,0,0,0,...,1.0,1.0,0,1.0,1,0.0,1,0.0,1,65
892805,1488012,5,6,1,0,0,0,0,0,0,...,1.0,1.0,0,0.0,1,1.0,1,2.0,1,10
892806,1488014,0,6,1,0,0,0,0,0,0,...,1.0,NaN,0,0.0,7,1.0,1,0.0,1,92
892807,1488015,0,3,0,1,0,0,0,0,0,...,1.0,1.0,0,0.0,0,1.0,0,2.0,1,95
892808,1488018,1,6,1,0,0,0,0,0,0,...,1.0,NaN,0,NaN,11,1.0,1,0.0,1,19
892809,1488019,2,7,0,0,0,1,0,0,0,...,1.0,NaN,0,1.0,11,1.0,1,0.0,1,57
892810,1488020,0,6,0,0,0,1,0,0,0,...,1.0,NaN,0,0.0,1,1.0,1,0.0,1,65
892811,1488022,0,6,0,1,0,0,0,0,0,...,1.0,NaN,8,0.0,14,0.0,1,0.0,1,18
892812,1488023,5,5,0,0,1,0,0,0,0,...,1.0,NaN,0,0.0,10,1.0,0,0.0,1,83
892813,1488024,0,5,1,0,0,0,0,0,0,...,1.0,NaN,0,NaN,11,1.0,0,1.0,1,17
892814,1488025,6,5,0,0,0,1,0,0,0,...,0.0,NaN,0,1.0,10,1.0,1,0.0,1,28
892815,1488026,7,4,0,0,0,1,0,0,0,...,1.0,1.0,0,0.0,4,1.0,1,2.0,1,48

In [25]:
dataset.set_index('id',inplace=True)

### Count the number of NaN values in each column

In [26]:
for i,j in dataset.isna().sum().iteritems():
    if j != 0:
        print(i,j)

num18 161684
num19 1
num22 63805
cat1 307
cat2 145
cat3 8710
cat4 160
cat5 5
cat6 616911
cat8 400359
cat10 17331
cat12 877

### Drop Columns with more NaN

In [27]:
dataset=dataset.drop(columns=['cat6','cat8'])

### Fillna with average values

In [28]:
dataset=dataset.fillna(dataset.mean())

### Correlation

In [9]:
dataset.corr()

,id,num1,num2,num3,num4,num5,num6,num7,num8,num9,...,cat3,cat4,cat5,cat7,cat9,cat10,cat11,cat12,cat13,cat14
id,1.000000,0.001371,0.001223,0.000128,0.000896,-0.000095,-0.001076,0.000603,-0.000528,-0.001399,...,0.000631,0.000170,0.000796,0.000130,0.000561,0.000317,-0.001453,-0.000819,0.001205,0.000269
num1,0.001371,1.000000,0.224018,-0.276595,0.005495,0.188839,0.161537,0.001563,-0.015867,-0.021546,...,0.011855,-0.058415,-0.115702,0.078835,0.071793,-0.030278,0.140214,-0.105886,0.010634,0.008714
num2,0.001223,0.224018,1.000000,-0.045164,-0.059010,0.013140,0.110512,0.007588,-0.002767,0.000597,...,0.041130,-0.028102,-0.043945,0.073868,0.007350,-0.013395,0.004102,-0.012431,-0.009038,-0.024521
num3,0.000128,-0.276595,-0.045164,1.000000,-0.473712,-0.356126,-0.384710,-0.009138,-0.005917,-0.018126,...,0.010625,-0.076070,0.138243,-0.188519,-0.060408,-0.001548,0.039783,0.099675,-0.041091,-0.030297
num4,0.000896,0.005495,-0.059010,-0.473712,1.000000,-0.260295,-0.281188,0.008010,0.010002,0.037493,...,-0.014659,0.061481,-0.161905,0.199683,0.021842,0.035265,-0.125296,-0.059371,0.031223,0.049426
num5,-0.000095,0.188839,0.013140,-0.356126,-0.260295,1.000000,-0.211391,0.007605,0.010466,0.010084,...,0.006527,0.001746,-0.032912,0.088231,0.066556,-0.047777,0.044150,-0.010450,0.024389,0.037410
num6,-0.001076,0.161537,0.110512,-0.384710,-0.281188,-0.211391,1.000000,-0.004757,-0.013761,-0.028954,...,-0.003077,0.024782,0.039624,-0.071550,-0.011986,0.008228,0.048835,-0.048527,-0.006681,-0.053068
num7,0.000603,0.001563,0.007588,-0.009138,0.008010,0.007605,-0.004757,1.000000,0.064641,0.087200,...,0.001367,0.009728,-0.013800,0.014383,0.003692,-0.001723,-0.004528,0.008891,-0.001509,0.005813
num8,-0.000528,-0.015867,-0.002767,-0.005917,0.010002,0.010466,-0.013761,0.064641,1.000000,0.250363,...,0.001318,0.006019,-0.003799,0.007131,0.002441,-0.006641,-0.001443,0.017945,-0.002391,0.004245
num9,-0.001399,-0.021546,0.000597,-0.018126,0.037493,0.010084,-0.028954,0.087200,0.250363,1.000000,...,0.000106,0.017162,-0.016938,0.026893,0.005019,-0.010991,-0.010990,0.043587,-0.009035,0.009585
num10,-0.000978,-0.010891,0.000451,-0.007894,0.011637,0.008749,-0.011483,0.060582,0.191213,0.158442,...,0.002337,0.006541,-0.009641,0.015057,0.003358,-0.007913,-0.005432,0.014392,-0.002165,0.006416
num11,-0.001381,-0.023814,0.000850,-0.018969,0.035694,0.014289,-0.029874,0.253394,0.561438,0.889226,...,0.001294,0.018018,-0.018555,0.028599,0.005977,-0.012662,-0.010839,0.043624,-0.008369,0.011097
num12,-0.001100,0.120478,0.168257,0.016126,-0.118843,0.052646,0.063210,-0.021173,-0.059289,-0.119124,...,0.009740,0.022384,0.009703,-0.048208,0.000855,0.060778,0.015426,0.039211,0.016673,-0.016892
num13,-0.002104,0.037633,-0.016468,0.029017,-0.075276,0.007822,0.040701,-0.024498,-0.053626,-0.101583,...,0.002867,-0.000248,0.029609,-0.047098,-0.015316,0.042437,0.031375,0.017231,0.008330,-0.014233
num14,0.001402,0.098431,0.023655,-0.037073,0.022761,0.033962,-0.011321,0.008005,0.005050,0.029004,...,0.009424,0.058777,-0.055299,0.046105,0.034027,-0.033609,-0.006131,0.074898,-0.008853,0.010080
num15,0.000771,-0.109608,0.002811,-0.013726,0.078358,-0.033122,-0.039304,0.025550,0.065099,0.107738,...,-0.009224,-0.044335,0.006387,0.018603,-0.007334,-0.024092,-0.029546,-0.045547,-0.004180,0.007745
num16,-0.001127,0.102449,0.003517,-0.022473,-0.029513,-0.136901,0.191569,0.002867,0.009108,0.013696,...,-0.014809,0.179914,-0.077331,-0.009815,0.067437,-0.031435,-0.011369,0.061872,-0.022737,0.009233
num17,0.000794,0.186104,0.050653,-0.184481,0.073595,0.001219,0.147792,0.012187,0.001889,0.006889,...,-0.002644,0.228733,-0.213499,0.106574,0.090407,-0.008580,-0.020586,0.020992,0.019180,0.043008
num18,-0.000557,0.202513,0.062996,-0.250923,0.131772,0.049411,0.117913,0.014709,-0.002899,0.002345,...,-0.000499,0.223902,-0.242103,0.156845,0.082623,0.005814,-0.028228,-0.012093,0.029355,0.050521
num19,-0.000836,0.005727,-0.058849,0.017022,0.068356,-0.081678,-0.020497,0.000319,0.004402,0.006259,...,0.000785,0.110716,-0.089743,-0.056710,-0.031367,0.114793,-0.036524,0.116744,0.015468,-0.050232
num20,0.000889,0.161169,0.088012,-0.221585,0.209234,0.101544,-0.053424,0.014423,0.005415,0.017950,...,-0.018886,0.126956,-0.468359,0.570508,0.272326,-0.028106,-0.031064,-0.035484,-0.018329,0.037579
num21,0.000791,0.099797,0.049088,-0.273887,0.348200,0.051005,-0.095822,0.015718,0.001522,0.021324,...,-0.017793,0.169562,-0.484514,0.596037,0.205931,-0.007636,-0.367329,-0.058638,0.034428,0.048659
num22,-0.000063,0.112665,0.012120,-0.133821,0.119715,0.063953,-0.026253,-0.008712,-0.033737,-0.077791,...,-0.014967,-0.002858,-0.265101,0.513472,0.172211,-0.042528,0.077368,-0.224645,-0.007675,0.020398
num23,0.000205,-0.058217,-0.049367,-0.165867,0.197256,0.015942,-0.028519,0.000500,-0.006476,-0.000322,...,-0.009017,0.105760,-0.076191,0.084042,-0.018565,-0.000836,-0.373623,-0.049391,0.054170,-0.043604
der1,0.001519,0.000370,-0.000195,-0.000938,0.001137,0.000874,-0.000932,0.001307,-0.000897,-0.000169,...,-0.000119,-0.000211,-0.000340,-0.000925,0.000789,0.000189,0.000098,0.000126,0.002333,0.000147
der2,-0.000126,-0.000609,0.001019,0.001836,-0.001112,-0.001133,0.000022,0.000807,-0.000864,0.000864,...,-0.000660,0.000996,0.000278,-0.000761,-0.001046,0.000354,-0.000925,0.003071,0.000384,-0.001326
der3,-0.000201,0.000141,0.000038,-0.000871,0.000890,-0.000257,0.000339,0.001117,-0.000594,-0.000053,...,-0.000988,0.000452,0.000267,0.002359,-0.001215,-0.000683,-0.001071,-0.000193,-0.000714,0.000168
der4,0.000169,-0.001333,0.000550,-0.000128,0.000879,0.000110,-0.000930,0.000432,0.000808,-0.000134,...,-0.000922,-0.000558,-0.000662,-0.000875,-0.000576,0.000119,0.000319,0.000685,-0.001279,-0.001396
der5,-0.000741,0.000182,-0.001481,-0.001229,0.000272,0.000278,0.000973,0.001489,0.001810,-0.000226,...,0.002715,-0.000096,0.000334,0.001067,-0.000635,-0.000493,-0.000103,-0.002054,0.000470,0.000589
der6,-0.000939,-0.000375,-0.001216,0.000056,0.002032,-0.001285,-0.001132,0.000999,-0.002472,0.000448,...,0.001946,-0.000996,-0.000673,-0.001092,-0.000681,0.000516,0.000076,0.000661,-0.000712,0.000331
der7,0.000706,-0.001287,-0.000320,-0.000054,-0.000190,0.000604,-0.000293,0.002575,-0.001023,0.000223,...,0.000691,0.000253,0.001169,-0.000882,0.002438,-0.001157,0.001231,-0.000081,0.001037,-0.001302
der8,0.000303,0.001099,0.000717,0.000203,-0.000669,0.001503,-0.000932,0.000627,0.000219,0.000982,...,-0.000352,0.000770,-0.000107,0.000260,-0.000132,-0.001092,-0.000368,-0.000469,0.001133,-0.000581
der9,0.001442,0.000162,-0.001301,-0.000276,-0.000136,0.000409,0.000110,0.002893,0.000156,0.002002,...,0.000218,0.000810,-0.000258,0.000642,-0.000110,-0.001328,-0.000525,-0.000572,0.001054,0.000807
der10,-0.001056,-0.000440,-0.001928,0.001178,-0.000630,-0.000435,-0.000358,-0.000171,-0.000464,-0.000283,...,0.001905,-0.000830,0.001660,-0.001410,0.000145,-0.000487,0.000222,-0.001893,0.001601,0.001631
der11,0.001437,0.000243,-0.000565,-0.000361,-0.001430,0.000423,0.001657,-0.001071,0.000357,-0.001035,...,-0.001220,0.000627,0.001809,-0.000572,-0.001104,-0.000004,0.000664,0.000435,0.000475,0.000431
der12,-0.000061,0.001382,0.000604,-0.000721,-0.000635,0.001548,0.000147,0.001034,-0.001892,-0.001060,...,0.000975,0.002138,0.000043,0.000149,0.001580,-0.000999,0.001392,-0.000181,-0.001060,0.000661
der13,-0.000170,0.001224,0.000405,-0.000444,0.001042,0.000280,-0.000880,-0.000218,0.000182,0.000544,...,0.002052,-0.001030,-0.000793,-0.000067,-0.002158,0.000432,-0.000305,-0.001695,0.001150,0.000124
der14,0.000243,-0.000366,0.002275,-0.000623,0.000937,-0.000131,-0.000145,0.003085,-0.000250,-0.000637,...,0.001484,-0.000088,-0.000086,0.000501,-0.000123,-0.001133,-0.000947,0.000524,-0.002745,0.000329
der15,-0.002726,0.001161,0.001205,-0.000853,0.002054,0.000344,-0.001564,0.001022,0.000070,0.000400,...,-0.000016,0.000797,-0.000430,0.001127,0.000307,-0.000324,-0.000330,0.000693,-0.000933,-0.001154
der16,0.000225,-0.001052,-0.002502,0.002909,-0.000980,-0.001070,-0.001533,-0.000965,-0.001505,-0.001561,...,-0.000027,0.000831,0.000791,0.000763,0.001234,-0.000766,-0.000797,0.000975,-0.000918,-0.000729
der17,-0.000241,-0.000127,-0.001651,-0.000613,0.001598,-0.001061,-0.000017,0.000268,-0.000725,-0.000399,...,-0.001057,0.000181,0.000200,0.001425,-0.000104,0.000410,0.000621,0.000302,0.001216,0.002136
der18,-0.000168,-0.000817,0.001305,0.001225,-0.000922,0.000148,-0.000643,0.002071,-0.000299,0.000202,...,0.001963,-0.000334,0.000374,0.000327,-0.000074,-0.000448,0.000135,-0.000556,-0.000968,-0.000729
der19,0.000474,-0.001690,0.000335,0.000451,-0.001214,-0.000979,0.001728,0.000081,0.000031,0.001113,...,0.001875,-0.000990,0.002165,-0.001373,0.000035,-0.000020,-0.000893,0.000902,-0.002607,-0.000305
cat1,0.000963,-0.002224,-0.065450,-0.125597,0.016975,0.033331,0.106935,0.001288,0.001328,-0.000372,...,-0.009088,-0.001068,0.047366,-0.073663,-0.018744,0.025347,-0.001486,0.004894,0.011635,0.013779
cat2,-0.001660,0.066367,-0.095521,-0.299436,0.306118,0.044563,-0.010328,-0.001254,0.000604,-0.003228,...,0.008690,0.025486,0.002150,-0.045510,0.027528,0.086389,-0.009183,-0.043384,0.025957,-0.001442
cat3,0.000631,0.011855,0.041130,0.010625,-0.014659,0.006527,-0.003077,0.001367,0.001318,0.000106,...,1.000000,-0.036133,0.011911,-0.008728,-0.006743,0.001625,-0.000810,-0.000881,0.002604,-0.001202
cat4,0.000170,-0.058415,-0.028102,-0.076070,0.061481,0.001746,0.024782,0.009728,0.006019,0.017162,...,-0.036133,1.000000,-0.153461,0.069232,0.052933,0.076787,-0.060667,0.272100,0.005371,0.012338
cat5,0.000796,-0.115702,-0.043945,0.138243,-0.161905,-0.032912,0.039624,-0.013800,-0.003799,-0.016938,...,0.011911,-0.153461,1.000000,-0.273715,-0.251130,-0.010546,0.037223,-0.011220,-0.020269,-0.001744
cat7,0.000130,0.078835,0.073868,-0.188519,0.199683,0.088231,-0.071550,0.014383,0.007131,0.026893,...,-0.008728,0.069232,-0.273715,1.000000,0.195099,-0.051840,-0.047186,-0.039324,0.001075,0.072432
cat9,0.000561,0.071793,0.007350,-0.060408,0.021842,0.066556,-0.011986,0.003692,0.002441,0.005019,...,-0.006743,0.052933,-0.251130,0.195099,1.000000,0.012946,-0.015172,0.001104,-0.000018,0.027755
cat10,0.000317,-0.030278,-0.013395,-0.001548,0.035265,-0.047777,0.008228,-0.001723,-0.006641,-0.010991,...,0.001625,0.076787,-0.010546,-0.051840,0.012946,1.000000,-0.001521,0.004395,0.015438,-0.038141
cat11,-0.001453,0.140214,0.004102,0.039783,-0.125296,0.044150,0.048835,-0.004528,-0.001443,-0.010990,...,-0.000810,-0.060667,0.037223,-0.047186,-0.015172,-0.001521,1.000000,-0.016466,-0.032548,0.034539
cat12,-0.000819,-0.105886,-0.012431,0.099675,-0.059371,-0.010450,-0.048527,0.008891,0.017945,0.043587,...,-0.000881,0.272100,-0.011220,-0.039324,0.001104,0.004395,-0.016466,1.000000,-0.020732,-0.009384
cat13,0.001205,0.010634,-0.009038,-0.041091,0.031223,0.024389,-0.006681,-0.001509,-0.002391,-0.009035,...,0.002604,0.005371,-0.020269,0.001075,-0.000018,0.015438,-0.032548,-0.020732,1.000000,0.004290
cat14,0.000269,0.008714,-0.024521,-0.030297,0.049426,0.037410,-0.053068,0.005813,0.004245,0.009585,...,-0.001202,0.012338,-0.001744,0.072432,0.027755,-0.038141,0.034539,-0.009384,0.004290,1.000000

### Duplicates

In [10]:
for i in dataset.duplicated().items():
    if i==True:
        print (i)

### Load Model

In [20]:
import pickle
loaded_model = pickle.load(open("finalized_model", 'rb'))

### Prediction on Unseen data using Model

In [29]:
Predicted=loaded_model.predict(dataset)

In [32]:
Predicted.shape

(892816,)

In [33]:
pd.DataFrame(Predicted)

        0
0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
...    ..
892786  0
892787  0
892788  0
892789  0
892790  0
892791  0
892792  0
892793  0
892794  0
892795  0
892796  0
892797  0
892798  0
892799  0
892800  0
892801  0
892802  0
892803  0
892804  0
892805  0
892806  0
892807  0
892808  0
892809  0
892810  0
892811  0
892812  0
892813  0
892814  0
892815  0

[892816 rows x 1 columns]

In [34]:
dataset.index.values

array([      0,       1,       2, ..., 1488024, 1488025, 1488026],
      dtype=int64)

### Creating DataFrame with id and target values

In [38]:
dataset2=pd.DataFrame(Predicted)

In [43]:
dataset2

        0       id
0       0        0
1       0        1
2       0        2
3       0        3
4       0        4
5       0        5
6       0        6
7       0        8
8       0       10
9       0       11
10      0       12
11      0       14
12      0       15
13      0       18
14      0       21
15      0       23
16      0       24
17      0       25
18      0       27
19      0       29
20      0       30
21      0       31
22      0       32
23      0       33
24      0       37
25      0       38
26      0       39
27      0       40
28      0       41
29      0       42
...    ..      ...
892786  0  1487982
892787  0  1487984
892788  0  1487985
892789  0  1487986
892790  0  1487987
892791  0  1487989
892792  0  1487991
892793  0  1487993
892794  0  1487995
892795  0  1487997
892796  0  1487998
892797  0  1487999
892798  0  1488000
892799  0  1488002
892800  0  1488003
892801  0  1488004
892802  0  1488006
892803  0  1488007
892804  0  1488010
892805  0  1488012
892806  0  1488014
892807  0  1488015
892808  0  1488018
892809  0  1488019
892810  0  1488020
892811  0  1488022
892812  0  1488023
892813  0  1488024
892814  0  1488025
892815  0  1488026

[892816 rows x 2 columns]

In [41]:
dataset2['id']=dataset.index.values

In [42]:
dataset2

        0       id
0       0        0
1       0        1
2       0        2
3       0        3
4       0        4
5       0        5
6       0        6
7       0        8
8       0       10
9       0       11
10      0       12
11      0       14
12      0       15
13      0       18
14      0       21
15      0       23
16      0       24
17      0       25
18      0       27
19      0       29
20      0       30
21      0       31
22      0       32
23      0       33
24      0       37
25      0       38
26      0       39
27      0       40
28      0       41
29      0       42
...    ..      ...
892786  0  1487982
892787  0  1487984
892788  0  1487985
892789  0  1487986
892790  0  1487987
892791  0  1487989
892792  0  1487991
892793  0  1487993
892794  0  1487995
892795  0  1487997
892796  0  1487998
892797  0  1487999
892798  0  1488000
892799  0  1488002
892800  0  1488003
892801  0  1488004
892802  0  1488006
892803  0  1488007
892804  0  1488010
892805  0  1488012
892806  0  1488014
892807  0  1488015
892808  0  1488018
892809  0  1488019
892810  0  1488020
892811  0  1488022
892812  0  1488023
892813  0  1488024
892814  0  1488025
892815  0  1488026

[892816 rows x 2 columns]

In [56]:
dataset2.columns

Index(['Target'], dtype='object')

### Renaming Column names

In [51]:
dataset2 = dataset2.rename(columns={0: 'Target'})

In [54]:
dataset2.set_index('id',inplace=True)

In [55]:
dataset2

         Target
id
0             0
1             0
2             0
3             0
4             0
5             0
6             0
8             0
10            0
11            0
12            0
14            0
15            0
18            0
21            0
23            0
24            0
25            0
27            0
29            0
30            0
31            0
32            0
33            0
37            0
38            0
39            0
40            0
41            0
42            0
...         ...
1487982       0
1487984       0
1487985       0
1487986       0
1487987       0
1487989       0
1487991       0
1487993       0
1487995       0
1487997       0
1487998       0
1487999       0
1488000       0
1488002       0
1488003       0
1488004       0
1488006       0
1488007       0
1488010       0
1488012       0
1488014       0
1488015       0
1488018       0
1488019       0
1488020       0
1488022       0
1488023       0
1488024       0
1488025       0
1488026       0

[892816 rows x 1 columns]

### Looking for Target=1

In [61]:
Predicted.nonzero()

(array([], dtype=int64),)

### Calculating corresponding probabilities

In [64]:
loaded_model.predict_proba(dataset)

array([[0.97196395, 0.02803605],
       [0.97133256, 0.02866744],
       [0.97232056, 0.02767944],
       ...,
       [0.97105005, 0.02894995],
       [0.97713381, 0.02286619],
       [0.96656943, 0.03343057]])

### Probability of Target being 1

In [77]:
loaded_model.predict_proba(dataset)[:,1]

array([0.02803605, 0.02866744, 0.02767944, ..., 0.02894995, 0.02286619,
       0.03343057])

### Dataset with Probabilities

In [66]:
dataset3=dataset2.drop('Target',axis=1)

In [67]:
dataset3

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 8, 10, 11, 12, 14, 15, 18, 21, 23, 24, 25, 27, 29, 30, 31, 32, 33, 37, 38, 39, 40, 41, 42, 44, 45, 47, 49, 51, 52, 53, 54, 55, 56, 57, 59, 60, 62, 63, 67, 68, 69, 70, 71, 73, 75, 76, 81, 82, 83, 86, 87, 88, 91, 92, 94, 97, 100, 102, 103, 105, 106, 108, 113, 114, 115, 118, 122, 124, 126, 128, 129, 130, 131, 132, 133, 134, 135, 136, 139, 140, 141, 146, 148, 151, 152, 154, 157, 158, 159, 161, 164, 165, 167, ...]

[892816 rows x 0 columns]

In [78]:
dataset3['target']=loaded_model.predict_proba(dataset)[:,1]

In [79]:
dataset3

           target
id
0        0.028036
1        0.028667
2        0.027679
3        0.019923
4        0.035332
5        0.034040
6        0.031188
8        0.022977
10       0.052027
11       0.057813
12       0.037054
14       0.025034
15       0.056247
18       0.059211
21       0.051206
23       0.027995
24       0.033486
25       0.025087
27       0.014914
29       0.060822
30       0.031495
31       0.044556
32       0.041593
33       0.017032
37       0.036486
38       0.025916
39       0.086445
40       0.033309
41       0.031598
42       0.024887
...           ...
1487982  0.023557
1487984  0.032191
1487985  0.040243
1487986  0.029679
1487987  0.039579
1487989  0.024953
1487991  0.023457
1487993  0.041213
1487995  0.032773
1487997  0.028645
1487998  0.036938
1487999  0.065320
1488000  0.048266
1488002  0.029448
1488003  0.033073
1488004  0.026688
1488006  0.028916
1488007  0.027628
1488010  0.024012
1488012  0.033119
1488014  0.027927
1488015  0.042082
1488018  0.028296
1488019  0.015879
1488020  0.024827
1488022  0.064641
1488023  0.050562
1488024  0.028950
1488025  0.022866
1488026  0.033431

[892816 rows x 1 columns]

### Creating a csv to write the result

In [83]:
dataset3.to_csv("Output.csv")

### Reading output file

In [86]:
pd.read_csv("Output.csv")

             id    target
0             0  0.028036
1             1  0.028667
2             2  0.027679
3             3  0.019923
4             4  0.035332
5             5  0.034040
6             6  0.031188
7             8  0.022977
8            10  0.052027
9            11  0.057813
10           12  0.037054
11           14  0.025034
12           15  0.056247
13           18  0.059211
14           21  0.051206
15           23  0.027995
16           24  0.033486
17           25  0.025087
18           27  0.014914
19           29  0.060822
20           30  0.031495
21           31  0.044556
22           32  0.041593
23           33  0.017032
24           37  0.036486
25           38  0.025916
26           39  0.086445
27           40  0.033309
28           41  0.031598
29           42  0.024887
...         ...       ...
892786  1487982  0.023557
892787  1487984  0.032191
892788  1487985  0.040243
892789  1487986  0.029679
892790  1487987  0.039579
892791  1487989  0.024953
892792  1487991  0.023457
892793  1487993  0.041213
892794  1487995  0.032773
892795  1487997  0.028645
892796  1487998  0.036938
892797  1487999  0.065320
892798  1488000  0.048266
892799  1488002  0.029448
892800  1488003  0.033073
892801  1488004  0.026688
892802  1488006  0.028916
892803  1488007  0.027628
892804  1488010  0.024012
892805  1488012  0.033119
892806  1488014  0.027927
892807  1488015  0.042082
892808  1488018  0.028296
892809  1488019  0.015879
892810  1488020  0.024827
892811  1488022  0.064641
892812  1488023  0.050562
892813  1488024  0.028950
892814  1488025  0.022866
892815  1488026  0.033431

[892816 rows x 2 columns]